# Generated by Django 5.0.14 on 2025-11-23 23:25

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_doc', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte'), ('RC', 'Registro Civil'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=2)),
                ('num_doc', models.CharField(max_length=20, unique=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('direccion', models.CharField(blank=True, default='No aplica', max_length=200, null=True)),
                ('celular', models.CharField(blank=True, default='No aplica', max_length=20, null=True)),
                ('ciudad_residencia', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo_Medicamentos',
            fields=[
                ('cod_med', models.AutoField(primary_key=True, serialize=False)),
                ('nom_med', models.CharField(max_length=150, unique=True)),
                ('principio_activo', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('proveedor_principal', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Catálogo de Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_dept', models.AutoField(primary_key=True, serialize=False)),
                ('nom_dept', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_esp', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sedes_Hospitalarias',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nom_sede', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('es_nodo_central', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cod_pac', models.CharField(default='PAC_TEMP', editable=False, max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_cita', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('PENDIENTE', 'Pendiente')], default='PROGRAMADA', max_length=20)),
                ('id_dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashier.departamentos')),
            ],
            options={
                'verbose_name_plural': 'Citas',
            },
        ),
        migrations.CreateModel(
            name='Historias_Clinicas',
            fields=[
                ('cod_hist', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.TextField()),
                ('diagnostico', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_cita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cashier.citas')),
            ],
            options={
                'verbose_name_plural': 'Historias Clínicas',
            },
        ),
        migrations.CreateModel(
            name='Prescripciones',
            fields=[
                ('id_presc', models.BigAutoField(primary_key=True, serialize=False)),
                ('dosis', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion_dias', models.IntegerField()),
                ('cantidad_total', models.IntegerField(blank=True, null=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('cod_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.historias_clinicas')),
                ('cod_med', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashier.catalogo_medicamentos')),
            ],
            options={
                'verbose_name_plural': 'Prescripciones',
            },
        ),
        migrations.AddField(
            model_name='departamentos',
            name='id_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.sedes_hospitalarias'),
        ),
        migrations.CreateModel(
            name='Reportes_Generados',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('parametros_json', models.TextField(blank=True, null=True)),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashier.sedes_hospitalarias')),
                ('id_emp_generador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashier.empleados')),
            ],
            options={
                'verbose_name_plural': 'Reportes Generados',
            },
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('cod_eq', models.AutoField(primary_key=True, serialize=False)),
                ('nom_eq', models.CharField(max_length=100)),
                ('marca_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_equipo', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Dado de Baja')], max_length=20)),
                ('fecha_ultimo_maint', models.DateField(blank=True, null=True)),
                ('id_dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashier.departamentos')),
                ('responsable_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_a_cargo', to='cashier.empleados')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.departamentos'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.especialidades'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashier.roles'),
        ),
        migrations.AddField(
            model_name='citas',
            name='id_emp',
            field=models.ForeignKey(limit_choices_to={'id_rol__nombre_rol': 'Médico'}, on_delete=django.db.models.deletion.PROTECT, to='cashier.empleados'),
        ),
        migrations.CreateModel(
            name='Auditoria_Accesos',
            fields=[
                ('id_evento', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('tabla_afectada', models.CharField(blank=True, max_length=50, null=True)),
                ('id_registro_afectado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('id_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.empleados')),
            ],
            options={
                'verbose_name_plural': 'Auditoría de Accesos',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.AddField(
            model_name='citas',
            name='cod_pac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashier.pacientes'),
        ),
        migrations.CreateModel(
            name='Inventario_Farmacia',
            fields=[
                ('id_inv', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_actual', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cod_med', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashier.catalogo_medicamentos')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashier.sedes_hospitalarias')),
            ],
            options={
                'verbose_name_plural': 'Inventario de Farmacia',
                'unique_together': {('id_sede', 'cod_med')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='citas',
            unique_together={('id_emp', 'fecha_hora')},
        ),
    ]
